package org.example;
import java.util.ArrayList;
import java.util.Collections;

public class EloRip
{

    public static void main(String[] args) {
        ArrayList<String> listaChampiona = new ArrayList<>();
        ArrayList<Integer> listaBrojevaZaIzvlacenjeNasumicnogChampiona = new ArrayList<>();
        listaChampiona.add("Aatrox");
        listaChampiona.add("Ahri");
        listaChampiona.add("Akali");
        listaChampiona.add("Alistar");
        listaChampiona.add("Amumu");
        listaChampiona.add("Anivia");
        listaChampiona.add("Annie");
        listaChampiona.add("Aphelios");
        listaChampiona.add("Ashe");
        listaChampiona.add("Aurelion Sol");
        listaChampiona.add("Azir");
        listaChampiona.add("Bard");
        listaChampiona.add("Blitzcrank");
        listaChampiona.add("Brand");
        listaChampiona.add("Braum");
        listaChampiona.add("Caitlyn");
        listaChampiona.add("Camille");
        listaChampiona.add("Cassiopeia");
        listaChampiona.add("Cho'Gath");
        listaChampiona.add("Corki");
        listaChampiona.add("Darius");
        listaChampiona.add("Diana");
        listaChampiona.add("Dr. Mundo");
        listaChampiona.add("Draven");
        listaChampiona.add("Ekko");
        listaChampiona.add("Elise");
        listaChampiona.add("Evelynn");
        listaChampiona.add("Ezreal");
        listaChampiona.add("Fiddlesticks");
        listaChampiona.add("Fiora");
        listaChampiona.add("Fizz");
        listaChampiona.add("Galio");
        listaChampiona.add("Gangplank");
        listaChampiona.add("Garen");
        listaChampiona.add("Gnar");
        listaChampiona.add("Gragas");
        listaChampiona.add("Graves");
        listaChampiona.add("Hecarim");
        listaChampiona.add("Heimerdinger");
        listaChampiona.add("Illaoi");
        listaChampiona.add("Irelia");
        listaChampiona.add("Ivern");
        listaChampiona.add("Janna");
        listaChampiona.add("Jarvan IV");
        listaChampiona.add("Jax");
        listaChampiona.add("Jayce");
        listaChampiona.add("Jhin");
        listaChampiona.add("Jinx");
        listaChampiona.add("Kai'Sa");
        listaChampiona.add("Kalista");
        listaChampiona.add("Karma");
        listaChampiona.add("Karthus");
        listaChampiona.add("Kassadin");
        listaChampiona.add("Katarina");
        listaChampiona.add("Kayle");
        listaChampiona.add("Kayn");
        listaChampiona.add("Kennen");
        listaChampiona.add("Kha'Zix");
        listaChampiona.add("Kindred");
        listaChampiona.add("Kled");
        listaChampiona.add("Kog'Maw");
        listaChampiona.add("LeBlanc");
        listaChampiona.add("Lee Sin");
        listaChampiona.add("Leona");
        listaChampiona.add("Lillia");
        listaChampiona.add("Lissandra");
        listaChampiona.add("Lucian");
        listaChampiona.add("Lulu");
        listaChampiona.add("Lux");
        listaChampiona.add("Malphite");
        listaChampiona.add("Malzahar");
        listaChampiona.add("Maokai");
        listaChampiona.add("Master Yi");
        listaChampiona.add("Miss Fortune");
        listaChampiona.add("Mordekaiser");
        listaChampiona.add("Morgana");
        listaChampiona.add("Nami");
        listaChampiona.add("Nasus");
        listaChampiona.add("Nautilus");
        listaChampiona.add("Neeko");
        listaChampiona.add("Nidalee");
        listaChampiona.add("Nocturne");
        listaChampiona.add("Nunu & Willump");
        listaChampiona.add("Olaf");
        listaChampiona.add("Orianna");
        listaChampiona.add("Ornn");
        listaChampiona.add("Pantheon");
        listaChampiona.add("Poppy");
        listaChampiona.add("Pyke");
        listaChampiona.add("Qiyana");
        listaChampiona.add("Quinn");
        listaChampiona.add("Rakan");
        listaChampiona.add("Rammus");
        listaChampiona.add("Rek'Sai");
        listaChampiona.add("Renekton");
        listaChampiona.add("Rengar");
        listaChampiona.add("Riven");
        listaChampiona.add("Rumble");
        listaChampiona.add("Ryze");
        listaChampiona.add("Samira");
        listaChampiona.add("Sejuani");
        listaChampiona.add("Senna");
        listaChampiona.add("Seraphine");
        listaChampiona.add("Sett");
        listaChampiona.add("Shaco");
        listaChampiona.add("Shen");
        listaChampiona.add("Shyvana");
        listaChampiona.add("Singed");
        listaChampiona.add("Sion");
        listaChampiona.add("Sivir");
        listaChampiona.add("Skarner");
        listaChampiona.add("Sona");
        listaChampiona.add("Soraka");
        listaChampiona.add("Swain");
        listaChampiona.add("Sylas");
        listaChampiona.add("Syndra");
        listaChampiona.add("Tahm Kench");
        listaChampiona.add("Taliyah");
        listaChampiona.add("Talon");
        listaChampiona.add("Taric");
        listaChampiona.add("Teemo");
        listaChampiona.add("Thresh");
        listaChampiona.add("Tristana");
        listaChampiona.add("Trundle");
        listaChampiona.add("Tryndamere");
        listaChampiona.add("Twisted Fate");
        listaChampiona.add("Twitch");
        listaChampiona.add("Udyr");
        listaChampiona.add("Urgot");
        listaChampiona.add("Varus");
        listaChampiona.add("Vayne");
        listaChampiona.add("Veigar");
        listaChampiona.add("Vel'Koz");
        listaChampiona.add("Vi");
        listaChampiona.add("Viktor");
        listaChampiona.add("Vladimir");
        listaChampiona.add("Volibear");
        listaChampiona.add("Warwick");
        listaChampiona.add("Wukong");
        listaChampiona.add("Xayah");
        listaChampiona.add("Xerath");
        listaChampiona.add("Xin Zhao");
        listaChampiona.add("Yasuo");
        listaChampiona.add("Yone");
        listaChampiona.add("Yorick");
        listaChampiona.add("Yuumi");
        listaChampiona.add("Zac");
        listaChampiona.add("Zed");
        listaChampiona.add("Ziggs");
        listaChampiona.add("Zilean");
        listaChampiona.add("Naafiri");
        listaChampiona.add("Milio");
        listaChampiona.add("Briar");
        listaChampiona.add("Hwei");
        listaChampiona.add("Renata Glasc");
        listaChampiona.add("Zeri");
        listaChampiona.add("Bel'Veth");
        listaChampiona.add("Nilah");
        listaChampiona.add("K'Sante");
        listaChampiona.add("Viego");
        listaChampiona.add("Gwen");
        listaChampiona.add("Akshan");
        listaChampiona.add("Vex");
        listaChampiona.add("Rell");
        for(int i=0;i<164;i++)listaBrojevaZaIzvlacenjeNasumicnogChampiona.add(i);
        Collections.shuffle(listaBrojevaZaIzvlacenjeNasumicnogChampiona);
        System.out.println("Elo.Rip kaze : "+listaChampiona.get(listaBrojevaZaIzvlacenjeNasumicnogChampiona.get(0)));
    }
}
